service_name: 'e99f19bc-2506-4265-b368-763fa8e4c1e2'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://0a6e-194-54-176-70.ngrok.io
  public_url: https://0a6e-194-54-176-70.ngrok.io
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: pg5746
